blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts',
    ),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:id>/delete/', views.delete_post, name='delete_post'),
    path('posts/<int:id>/comment/', views.add_comment, name='add_comment'),
    path(
        'posts/<int:post_id>/edit_comment/<int:comment_id>/',
        views.edit_comment,
        name='edit_comment',
    ),
    path(
        'posts/<int:post_id>/delete_comment/<int:comment_id>/',
        views.delete_comment,
        name='delete_comment',
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'profile/<str:username>/edit/',
        views.edit_profile,
        name='profile_edit',
    ),
]

blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from blog import views as blog_views

handler403 = 'blogicum.views.csrf_failure'
handler404 = 'blogicum.views.page_not_found'
handler500 = 'blogicum.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/', blog_views.register, name='registration'),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blogicum/blog/models.py
"""Models for blog app."""
from django.contrib.auth import get_user_model
from django.db import models

from core import models as published


User = get_user_model()


class Category(published.PublishedModel):
    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name='Заголовок',
    )
    description = models.TextField(
        blank=False,
        verbose_name='Описание',
    )
    slug = models.SlugField(
        unique=True,
        blank=False,
        verbose_name='Идентификатор',
        help_text=(
            'Идентификатор страницы для URL; '
            'разрешены символы латиницы, цифры, дефис и подчёркивание.'
        ),
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Location(published.PublishedModel):
    name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name='Название места',
    )

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'

    def __str__(self):
        return self.name


class Post(published.PublishedModel):
    title = models.CharField(
        max_length=256,
        blank=False,
        verbose_name='Заголовок',
    )
    text = models.TextField(
        blank=False,
        verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        blank=False,
        verbose_name='Дата и время публикации',
        help_text=(
            'Если установить дату и время в будущем — '
            'можно делать отложенные публикации.'
        ),
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=False,
        verbose_name='Автор публикации',
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Местоположение',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=False,
        null=True,
        verbose_name='Категория',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name='Изображение',
    )

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'Комментарии'

blogicum/blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Comment, Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'pub_date', 'category', 'location', 'image']
        widgets = {
            'pub_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

blogicum/blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.paginator import Paginator
from django.db.models import Prefetch, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    ListView,
    UpdateView,
)
from django.views.generic.detail import SingleObjectMixin

from .forms import CommentForm, PostForm, RegistrationForm
from .models import Category, Comment, Post

User = get_user_model()


class PostListView(ListView):

    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        return (
            Post.objects
            .select_related('location', 'category', 'author')
            .prefetch_related('comments')
            .filter(
                Q(pub_date__lte=timezone.now())
                & Q(is_published__exact=True)
                & Q(category__is_published__exact=True)
            )
            .order_by('-pub_date')
        )


index = PostListView.as_view()


class PostDetailView(DetailView):

    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return (
            Post.objects
            .select_related('location', 'category', 'author')
            .prefetch_related('comments__author')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        is_published = (
            post.pub_date <= timezone.now()
            and post.is_published
            and post.category
            and post.category.is_published
        )
        if not is_published:
            if (
                not self.request.user.is_authenticated
                or self.request.user != post.author
            ):
                raise Http404

        comment_form = CommentForm()
        comments = post.comments.order_by('created_at')
        context['comment_form'] = comment_form
        context['comments'] = comments
        return context


post_detail = PostDetailView.as_view()


class CategoryPostListView(ListView):

    model = Post
    template_name = 'blog/category.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        self.category = get_object_or_404(
            Category,
            slug=self.kwargs['category_slug'],
            is_published=True,
        )
        return (
            Post.objects
            .select_related('location', 'category', 'author')
            .prefetch_related('comments')
            .filter(
                Q(pub_date__lte=timezone.now())
                & Q(is_published__exact=True)
                & Q(category__is_published__exact=True)
                & Q(category__slug__exact=self.kwargs['category_slug'])
            )
            .order_by('-pub_date')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


category_posts = CategoryPostListView.as_view()


class ProfileView(ListView):

    model = Post
    template_name = 'blog/profile.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        self.profile_user = get_object_or_404(
            User, username=self.kwargs['username']
        )

        posts_qs = Post.objects.filter(author=self.profile_user).select_related(
            'location', 'category', 'author'
        ).prefetch_related('comments')

        if (
            self.request.user.is_authenticated
            and self.request.user == self.profile_user
        ):
            return posts_qs.order_by('-pub_date')
        else:
            return (
                posts_qs
                .filter(
                    Q(pub_date__lte=timezone.now())
                    & Q(is_published__exact=True)
                    & Q(category__is_published__exact=True)
                )
                .order_by('-pub_date')
            )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_user'] = self.profile_user
        context['profile'] = self.profile_user
        context['is_owner'] = (
            self.request.user.is_authenticated
            and self.request.user == self.profile_user
        )
        return context


profile = ProfileView.as_view()


class CreatePostView(CreateView):

    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        if not form.instance.pub_date:
            form.instance.pub_date = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'blog:profile', kwargs={'username': self.request.user.username}
        )


create_post = login_required(CreatePostView.as_view())


class EditPostView(UpdateView):

    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'
    pk_url_kwarg = 'id'

    def get_queryset(self):
        return Post.objects.all()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user:
            return redirect('blog:post_detail', id=obj.pk)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        if not form.instance.pub_date:
            form.instance.pub_date = timezone.now()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'id': self.object.pk}
        )

    def get_object(self, queryset=None):
        return super().get_object(queryset)


edit_post = login_required(EditPostView.as_view())


class DeletePostView(DeleteView):

    model = Post
    template_name = 'blog/detail.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('blog:index')

    def get_queryset(self):
        return Post.objects.all()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user and not request.user.is_staff:
            return redirect('blog:post_detail', id=obj.pk)
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return super().get_object(queryset)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['confirm_delete'] = True
        return context


delete_post = login_required(DeletePostView.as_view())


class AddCommentView(SingleObjectMixin, FormView):

    model = Post
    form_class = CommentForm
    template_name = 'blog/detail.html'
    pk_url_kwarg = 'id'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return redirect('blog:post_detail', id=self.object.pk)


add_comment = login_required(AddCommentView.as_view())


class EditCommentView(UpdateView):

    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_id'

    def get_queryset(self):
        return Comment.objects.all()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user:
            return redirect('blog:post_detail', id=self.kwargs.get('post_id'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(
            Post, pk=self.kwargs['post_id']
        )
        return context

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'id': self.object.post.pk}
        )

    def get_object(self, queryset=None):
        return super().get_object(queryset)


edit_comment = login_required(EditCommentView.as_view())


class DeleteCommentView(DeleteView):

    model = Comment
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_id'

    def get_queryset(self):
        return Comment.objects.all()

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != request.user and not request.user.is_staff:
            return redirect('blog:post_detail', id=self.kwargs.get('post_id'))
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'id': self.object.post.pk}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(
            Post, pk=self.kwargs['post_id']
        )
        context['confirm_delete'] = True
        return context

    def get_object(self, queryset=None):
        return super().get_object(queryset)


delete_comment = login_required(DeleteCommentView.as_view())


class RegistrationView(CreateView):

    form_class = RegistrationForm
    template_name = 'registration/registration_form.html'
    success_url = reverse_lazy('login')


register = RegistrationView.as_view()


class EditProfileView(UpdateView):

    model = User
    fields = ('first_name', 'last_name', 'username', 'email')

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Публикации в категории - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Редактирование комментария
  {% else %}
    Удаление комментария
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Редактирование комментария
          {% else %}
            Удаление комментария
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Отправить" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.pub_date|date:"d E Y" }} | {% if form.instance.location and form.instance.location.is_published %}{{ form.instance.location.name }}{% else %}Планета Земля{% endif %}<br>
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  {% if confirm_delete %}
    <h1>Подтверждение удаления публикации</h1>
    <article class="card mb-5">
      <div class="card-body">
        <h3>{{ post.title }}</h3>
        {% if post.image %}
          <img src="{{ post.image.url }}" alt="" class="img-fluid mb-3" style="max-width:400px;">
        {% endif %}
        <p>{{ post.text|linebreaksbr }}</p>
        <p class="text-muted"><small>
          От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
        </small></p>
      </div>
    </article>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Удалить публикацию</button>
      <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-secondary">Отмена</a>
    </form>
  {% else %}
    <article class="mb-5">
      <p class="text-muted"><small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small></p>
      <h3>{{ post.title }}</h3>
      {% if post.image %}
        <img src="{{ post.image.url }}" alt="" class="img-fluid mb-3" style="max-width:400px;">
      {% endif %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if request.user.is_authenticated and request.user == post.author %}
        <div class="mt-3">
          <a href="{% url 'blog:edit_post' post.id %}" class="btn btn-secondary">Редактировать</a>
          <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-danger">Удалить</a>
        </div>
      {% endif %}
    </article> 
    <section class="mt-5">
      <h4>Комментарии ({{ post.comments.count }})</h4>
      {% for comment in comments %}
        <div class="card mb-3">
          <div class="card-body">
            <p class="card-text">{{ comment.author.username }}: {{ comment.text|linebreaksbr }}</p>
            {% if request.user.is_authenticated and request.user == comment.author %}
              <div>
                <a href="{% url 'blog:edit_comment' post.id comment.id %}" class="btn btn-sm btn-secondary">Редактировать</a>
                <a href="{% url 'blog:delete_comment' post.id comment.id %}" class="btn btn-sm btn-danger">Удалить</a>
              </div>
            {% endif %}
          </div>
        </div>
      {% empty %}
        <p>Комментариев пока нет.</p>
      {% endfor %}

      {% if request.user.is_authenticated %}
        <h5>Добавить комментарий</h5>
        <form method="post" action="{% url 'blog:add_comment' post.id %}" class="mt-3">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <button type="submit" class="btn btn-primary mt-3">Отправить</button>
        </form>
      {% else %}
        <div class="alert alert-info" role="alert">
          Только авторизованные пользователи могут оставлять комментарии.
        </div>
      {% endif %}
    </section>
  {% endif %}
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}Главная | Блогикум{% endblock %}
{% block content %}
  <h1>Публикации</h1>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% empty %}
    <p>Публикаций пока нет.</p>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}
  Страница пользователя {{ profile.username }}
{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}{{ profile.username }}{% endif %}</li>
      <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined|date:"d E Y, H:i" }}</li>
      <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if is_owner %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:profile_edit' profile.username %}">Редактировать профиль</a>
      <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
      {% endif %}
    </ul>
  </small>
  <br>
  <h3 class="mb-5 text-center">Публикации пользователя</h3>
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  Редактирование профиля
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Редактирование профиля - {{ request.user.username }}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}